import { useEffect, useState } from 'react'
import Tile from './Tile'
//import maze from "./maze"

function App() {
    const [i,setI]=useState(0)
    const [maze,setMaze]=useState([
        [
          { top: false, right: true, bottom: true, left: false, num: 0, v: false },
          { top: false, right: true, bottom: false, left: true, num: 0, v: false },
          { top: false, right: true, bottom: true, left: false, num: 0, v: false },
          { top: false, right: true, bottom: true, left: true, num: 3, v: false },
          { top: false, right: true, bottom: false, left: false, num: 3, v: false },
          { top: false, right: false, bottom: true, left: false, num: 3, v: false },
          { top: false, right: false, bottom: true, left: true, num: 3, v: false },
          { top: false, right: true, bottom: true, left: true, num: 3, v: false },
          { top: false, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: true, num: 14, v: false },
          { top: false, right: true, bottom: true, left: true, num: 14, v: false },
          { top: false, right: true, bottom: true, left: true, num: 14, v: false },
          { top: false, right: true, bottom: true, left: true, num: 14, v: false },
          { top: false, right: true, bottom: true, left: false, num: 14, v: false },
          { top: false, right: false, bottom: true, left: false, num: 14, v: false }
        ],
        [
          { top: false, right: true, bottom: true, left: false, num: 0, v: false },
          { top: true, right: true, bottom: false, left: false, num: 0, v: false },
          { top: false, right: true, bottom: true, left: true, num: 0, v: false },
          { top: true, right: true, bottom: false, left: true, num: 3, v: false },
          { top: true, right: false, bottom: false, left: false, num: 3, v: false },
          { top: false, right: false, bottom: true, left: true, num: 3, v: false },
          { top: true, right: true, bottom: true, left: true, num: 3, v: false },
          { top: true, right: true, bottom: true, left: true, num: 3, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: true, num: 14, v: false },
          { top: false, right: true, bottom: false, left: false, num: 14, v: false },
          { top: false, right: true, bottom: false, left: false, num: 14, v: false },
          { top: true, right: false, bottom: true, left: false, num: 14, v: false },
          { top: true, right: false, bottom: true, left: true, num: 14, v: false },
          { top: false, right: false, bottom: true, left: true, num: 14, v: false }
        ],
        [
          { top: true, right: true, bottom: false, left: false, num: 0, v: false },
          { top: true, right: false, bottom: true, left: false, num: 0, v: false },
          { top: false, right: true, bottom: true, left: true, num: 0, v: false },
          { top: true, right: true, bottom: true, left: true, num: 3, v: false },
          { top: true, right: false, bottom: true, left: true, num: 3, v: false },
          { top: true, right: false, bottom: true, left: true, num: 3, v: false },
          { top: true, right: false, bottom: false, left: true, num: 3, v: false },
          { top: false, right: true, bottom: true, left: true, num: 3, v: false },
          { top: false, right: true, bottom: true, left: true, num: 28, v: false },
          { top: false, right: false, bottom: true, left: false, num: 28, v: false },
          { top: false, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 14, v: false },
          { top: true, right: true, bottom: true, left: false, num: 14, v: false },
          { top: true, right: false, bottom: true, left: true, num: 14, v: false },
          { top: false, right: true, bottom: true, left: true, num: 14, v: false },
          { top: true, right: false, bottom: true, left: true, num: 58, v: false },
          { top: true, right: false, bottom: true, left: true, num: 58, v: false }
        ],
        [
          { top: true, right: false, bottom: false, left: false, num: 0, v: false },
          { top: true, right: true, bottom: true, left: true, num: 0, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: false, bottom: true, left: false, num: 62, v: false },
          { top: true, right: false, bottom: false, left: true, num: 62, v: false },
          { top: true, right: true, bottom: false, left: true, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 3, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: false, num: 28, v: false },
          { top: false, right: true, bottom: true, left: false, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: false, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: false, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 58, v: false },
          { top: false, right: true, bottom: true, left: false, num: 58, v: false },
          { top: true, right: false, bottom: true, left: true, num: 58, v: false }
        ],
        [
          { top: true, right: true, bottom: false, left: false, num: 0, v: false },
          { top: true, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: true, left: false, num: 81, v: false },
          { top: false, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: false, left: false, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: false, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: false, right: true, bottom: true, left: false, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: false, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: false, left: true, num: 58, v: false },
          { top: false, right: false, bottom: true, left: false, num: 58, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 0, v: false },
          { top: true, right: true, bottom: true, left: true, num: 81, v: false },
          { top: false, right: true, bottom: true, left: true, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: false, left: true, num: 62, v: false },
          { top: true, right: false, bottom: true, left: true, num: 62, v: false },
          { top: false, right: false, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: false, left: true, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: false, right: false, bottom: true, left: true, num: 28, v: false },
          { top: false, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: false, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: false, right: false, bottom: true, left: true, num: 8, v: false },
          { top: false, right: false, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: false, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 58, v: false },
          { top: false, right: false, bottom: false, left: true, num: 58, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 81, v: false },
          { top: false, right: true, bottom: true, left: false, num: 81, v: false },
          { top: false, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: false, bottom: false, left: false, num: 62, v: false },
          { top: false, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: true, left: false, num: 62, v: false },
          { top: false, right: true, bottom: true, left: true, num: 28, v: false },
          { top: false, right: false, bottom: true, left: false, num: 28, v: false },
          { top: true, right: false, bottom: false, left: true, num: 28, v: false },
          { top: false, right: true, bottom: false, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: false, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 58, v: false }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 81, v: false },
          { top: true, right: false, bottom: true, left: false, num: 81, v: false },
          { top: false, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: true, bottom: false, left: false, num: 62, v: false },
          { top: true, right: true, bottom: true, left: true, num: 145, v: false },
          { top: true, right: false, bottom: true, left: false, num: 145, v: false },
          { top: true, right: false, bottom: true, left: true, num: 145, v: false },
          { top: true, right: true, bottom: true, left: true, num: 145, v: false },
          { top: false, right: true, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: false, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: false, bottom: true, left: true, num: 28, v: false },
          { top: true, right: true, bottom: true, left: true, num: 28, v: false },
          { top: false, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: false, num: 8, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 81, v: false },
          { top: false, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: false, bottom: false, left: false, num: 81, v: false },
          { top: true, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: false, left: true, num: 62, v: false },
          { top: true, right: true, bottom: false, left: true, num: 145, v: false },
          { top: false, right: true, bottom: true, left: false, num: 145, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: false, right: true, bottom: false, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: false, bottom: true, left: false, num: 8, v: false },
          { top: false, right: false, bottom: true, left: true, num: 8, v: false }
        ],
        [
          { top: true, right: true, bottom: false, left: false, num: 81, v: false },
          { top: true, right: true, bottom: false, left: false, num: 81, v: false },
          { top: true, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 62, v: false },
          { top: true, right: false, bottom: true, left: true, num: 145, v: false },
          { top: false, right: true, bottom: false, left: true, num: 145, v: false },
          { top: true, right: true, bottom: true, left: true, num: 187, v: false },
          { top: true, right: false, bottom: true, left: false, num: 187, v: false },
          { top: true, right: false, bottom: true, left: true, num: 187, v: false },
          { top: true, right: true, bottom: false, left: true, num: 187, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: false, left: false, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 8, v: false },
          { top: false, right: false, bottom: false, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 8, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 81, v: false },
          { top: true, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: false, left: true, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 145, v: false },
          { top: true, right: true, bottom: true, left: false, num: 145, v: false },
          { top: true, right: true, bottom: false, left: true, num: 145, v: false },
          { top: true, right: true, bottom: true, left: true, num: 145, v: false },
          { top: false, right: true, bottom: true, left: true, num: 187, v: false },
          { top: true, right: true, bottom: true, left: true, num: 187, v: false },
          { top: true, right: true, bottom: false, left: false, num: 187, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 8, v: false },
          { top: false, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: false, bottom: false, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 8, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 81, v: false },
          { top: true, right: true, bottom: false, left: false, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 81, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: false, right: true, bottom: true, left: true, num: 145, v: false },
          { top: true, right: false, bottom: false, left: true, num: 145, v: false },
          { top: false, right: true, bottom: false, left: true, num: 145, v: false },
          { top: false, right: true, bottom: true, left: true, num: 187, v: false },
          { top: true, right: true, bottom: true, left: true, num: 187, v: false },
          { top: true, right: true, bottom: false, left: false, num: 187, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: false, right: false, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: true, bottom: false, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: false, num: 8, v: false },
          { top: true, right: false, bottom: false, left: false, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 8, v: false }
        ],
        [
          { top: false, right: false, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 81, v: false },
          { top: true, right: false, bottom: true, left: true, num: 220, v: false },
          { top: false, right: true, bottom: true, left: true, num: 220, v: false },
          { top: false, right: true, bottom: true, left: true, num: 145, v: false },
          { top: true, right: true, bottom: false, left: false, num: 145, v: false },
          { top: true, right: true, bottom: true, left: true, num: 145, v: false },
          { top: false, right: true, bottom: true, left: true, num: 187, v: false },
          { top: true, right: true, bottom: true, left: false, num: 187, v: false },
          { top: true, right: true, bottom: true, left: false, num: 187, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: false, num: 167, v: false },
          { top: false, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: false, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: true, bottom: true, left: true, num: 8, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false }
        ],
        [
          { top: false, right: false, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: false, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: false, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 145, v: false },
          { top: true, right: false, bottom: true, left: true, num: 220, v: false },
          { top: true, right: false, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: false, right: false, bottom: true, left: false, num: 167, v: false }
        ],
        [
          { top: false, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: false, left: false, num: 220, v: false },
          { top: false, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: false, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: false, bottom: true, left: false, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: false, bottom: true, left: false, num: 167, v: false }
        ],
        [
          { top: false, right: true, bottom: true, left: false, num: 220, v: false },
          { top: false, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: true, left: false, num: 220, v: false },
          { top: true, right: true, bottom: false, left: true, num: 220, v: false },
          { top: false, right: false, bottom: true, left: false, num: 220, v: false },
          { top: true, right: false, bottom: true, left: true, num: 220, v: false },
          { top: false, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: false, right: false, bottom: true, left: false, num: 167, v: false }
        ],
        [
          { top: true, right: true, bottom: false, left: false, num: 320, v: false },
          { top: true, right: false, bottom: true, left: false, num: 320, v: false },
          { top: true, right: false, bottom: true, left: true, num: 320, v: false },
          { top: true, right: true, bottom: true, left: true, num: 320, v: false },
          { top: true, right: false, bottom: false, left: true, num: 220, v: false },
          { top: false, right: false, bottom: true, left: true, num: 220, v: false },
          { top: true, right: false, bottom: false, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: false, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: false, bottom: true, left: false, num: 167, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false },
          { top: false, right: false, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: false, bottom: true, left: false, num: 167, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 320, v: false },
          { top: false, right: true, bottom: true, left: true, num: 320, v: false },
          { top: true, right: false, bottom: true, left: true, num: 320, v: false },
          { top: true, right: true, bottom: false, left: true, num: 320, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: true, bottom: true, left: true, num: 345, v: false },
          { top: true, right: true, bottom: true, left: true, num: 220, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: false, bottom: true, left: true, num: 167, v: false },
          { top: true, right: false, bottom: false, left: true, num: 167, v: false },
          { top: true, right: false, bottom: false, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: false, right: false, bottom: true, left: true, num: 167, v: false }
        ],
        [
          { top: true, right: true, bottom: true, left: false, num: 320, v: false },
          { top: false, right: true, bottom: false, left: true, num: 320, v: false },
          { top: false, right: true, bottom: true, left: false, num: 320, v: false },
          { top: true, right: true, bottom: false, left: true, num: 320, v: false },
          { top: true, right: false, bottom: true, left: true, num: 345, v: false },
          { top: false, right: false, bottom: false, left: true, num: 345, v: false },
          { top: true, right: true, bottom: true, left: true, num: 345, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: false, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: false, bottom: true, left: false, num: 167, v: false },
          { top: false, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: true, bottom: true, left: true, num: 167, v: false },
          { top: false, right: true, bottom: true, left: true, num: 167, v: false },
          { top: true, right: false, bottom: false, left: true, num: 167, v: false },
          { top: false, right: false, bottom: false, left: true, num: 167, v: false }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 320, v: false },
          { top: true, right: true, bottom: false, left: false, num: 320, v: false },
          { top: false, right: true, bottom: false, left: true, num: 320, v: false },
          { top: true, right: true, bottom: false, left: false, num: 320, v: false },
          { top: false, right: true, bottom: false, left: true, num: 345, v: false },
          { top: true, right: false, bottom: false, left: false, num: 345, v: false },
          { top: true, right: true, bottom: false, left: true, num: 345, v: false },
          { top: false, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: false, right: true, bottom: false, left: false, num: 167, v: false },
          { top: false, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: true, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: false, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: true, bottom: false, left: false, num: 167, v: false },
          { top: true, right: false, bottom: false, left: true, num: 167, v: false }
        ]
      ]
      )

    const newMaze = maze.flatMap((row) => row.map((obj) => obj));

    useEffect(()=>{
        setInterval(()=>{
            setI(prevI=>prevI+1)
            console.log("WTF")
            console.log(i)
        },1000)
    },[])
    let m=0;
    const mazeElements=newMaze.map((tile)=>{
        // console.log(tile)
        let classes=[]
        Object.keys(tile).forEach(key=>{
            if(key!="num" && tile[key]==true){
                classes.push(key)
            }
        })
        if(m==189){
            classes.push("center")
        }
        m++
        return (
            <div className={`tile ${classes.join(' ')}`}> {tile.num}</div>
        )
    })

    return (
        <div className='grid'>
            {mazeElements}
        </div>
    )
}

export default App
