import { useEffect, useState } from 'react'
import Tile from './Tile'
//import maze from "./maze"

function App() {
    const [i,setI]=useState(0)
    const [maze,setMaze]=useState([
        [
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: false, right: false, bottom: true, left: true, num: 0, v: true },
          { top: false, right: false, bottom: false, left: false, num: 0, v: true },
          { top: false, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 0, v: true },
          { top: false, right: false, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: true, num: 9, v: true },
          { top: false, right: false, bottom: false, left: false, num: 9, v: true },
          { top: false, right: false, bottom: true, left: false, num: 9, v: true },
          { top: false, right: true, bottom: false, left: false, num: 9, v: true },
          { top: false, right: false, bottom: false, left: true, num: 9, v: true },
          { top: false, right: false, bottom: false, left: false, num: 9, v: true },
          { top: false, right: true, bottom: true, left: false, num: 9, v: true },
          { top: false, right: true, bottom: false, left: true, num: 16, v: true },
          { top: false, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: false, bottom: true, left: false, num: 16, v: true },
          { top: false, right: false, bottom: false, left: false, num: 16, v: true }
        ],
        [
          { top: false, right: false, bottom: true, left: false, num: 0, v: true },
          { top: true, right: false, bottom: false, left: false, num: 0, v: true },
          { top: false, right: true, bottom: true, left: false, num: 0, v: true },
          { top: true, right: false, bottom: true, left: true, num: 0, v: true },
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: true, right: false, bottom: true, left: true, num: 0, v: true },
          { top: false, right: false, bottom: false, left: false, num: 0, v: true },
          { top: true, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: true, num: 9, v: true },
          { top: false, right: true, bottom: true, left: true, num: 9, v: true },
          { top: true, right: false, bottom: true, left: true, num: 9, v: true },
          { top: false, right: true, bottom: false, left: false, num: 9, v: true },
          { top: false, right: true, bottom: false, left: true, num: 9, v: true },
          { top: false, right: false, bottom: false, left: true, num: 9, v: true },
          { top: true, right: true, bottom: false, left: false, num: 9, v: true },
          { top: false, right: false, bottom: true, left: true, num: 16, v: true },
          { top: true, right: true, bottom: false, left: false, num: 16, v: true },
          { top: true, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: false, bottom: false, left: false, num: 16, v: true }
        ],
        [
          { top: true, right: false, bottom: false, left: false, num: 0, v: true },
          { top: false, right: true, bottom: true, left: false, num: 0, v: true },
          { top: true, right: false, bottom: false, left: true, num: 0, v: true },
          { top: true, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 0, v: true },
          { top: true, right: false, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: true, left: false, num: 0, v: true },
          { top: true, right: true, bottom: false, left: true, num: 7, v: true },
          { top: false, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 9, v: true },
          { top: true, right: false, bottom: false, left: true, num: 9, v: true },
          { top: false, right: false, bottom: false, left: false, num: 9, v: true },
          { top: false, right: false, bottom: false, left: false, num: 9, v: true },
          { top: false, right: true, bottom: true, left: false, num: 9, v: true },
          { top: false, right: true, bottom: false, left: true, num: 9, v: true },
          { top: true, right: false, bottom: false, left: true, num: 16, v: true },
          { top: false, right: false, bottom: true, left: false, num: 16, v: true },
          { top: true, right: true, bottom: true, left: false, num: 16, v: true },
          { top: false, right: false, bottom: false, left: true, num: 16, v: true }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: true, right: false, bottom: false, left: true, num: 0, v: true },
          { top: false, right: false, bottom: true, left: false, num: 0, v: true },
          { top: true, right: false, bottom: true, left: false, num: 0, v: true },
          { top: false, right: false, bottom: true, left: false, num: 0, v: true },
          { top: true, right: true, bottom: false, left: false, num: 0, v: true },
          { top: true, right: false, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 9, v: true },
          { top: false, right: true, bottom: true, left: false, num: 9, v: true },
          { top: false, right: true, bottom: true, left: true, num: 9, v: true },
          { top: false, right: false, bottom: true, left: true, num: 9, v: true },
          { top: true, right: true, bottom: false, left: false, num: 9, v: true },
          { top: false, right: true, bottom: true, left: true, num: 9, v: true },
          { top: false, right: false, bottom: false, left: true, num: 16, v: true },
          { top: true, right: true, bottom: false, left: false, num: 16, v: true },
          { top: true, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: false, bottom: false, left: false, num: 16, v: true }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: false, right: true, bottom: true, left: true, num: 0, v: true },
          { top: true, right: true, bottom: false, left: true, num: 0, v: true },
          { top: true, right: true, bottom: false, left: true, num: 0, v: true },
          { top: true, right: false, bottom: false, left: true, num: 0, v: true },
          { top: false, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: false, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: true, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: false, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 9, v: true },
          { top: false, right: true, bottom: true, left: false, num: 9, v: true },
          { top: true, right: false, bottom: false, left: true, num: 16, v: true },
          { top: false, right: true, bottom: false, left: false, num: 16, v: true },
          { top: false, right: true, bottom: true, left: true, num: 16, v: true },
          { top: true, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: false, bottom: false, left: false, num: 16, v: true }
        ],
        [
          { top: false, right: false, bottom: true, left: false, num: 0, v: true },
          { top: true, right: false, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: false, right: true, bottom: false, left: true, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 0, v: true },
          { top: true, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 16, v: true },
          { top: true, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: true, bottom: true, left: false, num: 16, v: true },
          { top: false, right: false, bottom: true, left: true, num: 16, v: true },
          { top: true, right: false, bottom: false, left: false, num: 16, v: true },
          { top: true, right: false, bottom: false, left: false, num: 16, v: true },
          { top: false, right: false, bottom: false, left: false, num: 16, v: true }
        ],
        [
          { top: true, right: false, bottom: false, left: false, num: 120, v: true },
          { top: true, right: true, bottom: false, left: false, num: 120, v: true },
          { top: false, right: false, bottom: false, left: true, num: 0, v: true },
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 0, v: true },
          { top: true, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: false, bottom: true, left: false, num: 16, v: true },
          { top: true, right: false, bottom: true, left: false, num: 16, v: true },
          { top: true, right: false, bottom: true, left: false, num: 16, v: true },
          { top: true, right: false, bottom: true, left: false, num: 16, v: true },
          { top: false, right: false, bottom: true, left: false, num: 16, v: true },
          { top: false, right: true, bottom: false, left: false, num: 16, v: true },
          { top: false, right: false, bottom: true, left: true, num: 16, v: true }
        ],
        [
          { top: false, right: false, bottom: true, left: false, num: 120, v: true },
          { top: false, right: true, bottom: false, left: false, num: 120, v: true },
          { top: false, right: true, bottom: true, left: true, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 0, v: true },
          { top: false, right: false, bottom: true, left: false, num: 0, v: true },
          { top: true, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: false, bottom: false, left: false, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: true, right: false, bottom: true, left: true, num: 16, v: true },
          { top: false, right: true, bottom: true, left: false, num: 16, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true }
        ],
        [
          { top: true, right: true, bottom: false, left: false, num: 160, v: true },
          { top: false, right: false, bottom: true, left: true, num: 120, v: true },
          { top: true, right: true, bottom: true, left: false, num: 120, v: true },
          { top: false, right: false, bottom: true, left: true, num: 0, v: true },
          { top: true, right: true, bottom: false, left: false, num: 0, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: false, left: false, num: 152, v: true },
          { top: false, right: false, bottom: false, left: true, num: 152, v: true }
        ],
        [
          { top: false, right: false, bottom: false, left: false, num: 160, v: true },
          { top: true, right: false, bottom: true, left: false, num: 160, v: true },
          { top: true, right: true, bottom: false, left: false, num: 160, v: true },
          { top: true, right: false, bottom: true, left: true, num: 0, v: true },
          { top: false, right: true, bottom: false, left: false, num: 0, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: false, bottom: false, left: false, num: 7, v: true },
          { top: true, right: false, bottom: false, left: false, num: 7, v: true },
          { top: true, right: false, bottom: true, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: true, right: false, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: false, left: false, num: 152, v: true },
          { top: true, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: true, bottom: false, left: false, num: 152, v: true },
          { top: false, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: false, bottom: false, left: false, num: 152, v: true }
        ],
        [
          { top: false, right: false, bottom: false, left: false, num: 160, v: true },
          { top: true, right: false, bottom: true, left: false, num: 160, v: true },
          { top: false, right: false, bottom: true, left: false, num: 160, v: true },
          { top: true, right: true, bottom: true, left: false, num: 160, v: true },
          { top: false, right: true, bottom: false, left: true, num: 0, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: false, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: false, num: 7, v: true },
          { top: true, right: false, bottom: true, left: false, num: 7, v: true },
          { top: true, right: false, bottom: true, left: false, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: false, bottom: true, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true },
          { top: false, right: false, bottom: false, left: false, num: 152, v: true }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 160, v: true },
          { top: true, right: true, bottom: false, left: true, num: 221, v: true },
          { top: true, right: false, bottom: true, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: true, left: true, num: 0, v: true },
          { top: true, right: true, bottom: true, left: false, num: 0, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: false, bottom: false, left: false, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: false, left: false, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 160, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: true, bottom: false, left: false, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: false, right: true, bottom: false, left: false, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: true, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: false, bottom: false, left: false, num: 152, v: true },
          { top: false, right: true, bottom: true, left: false, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 259, v: true }
        ],
        [
          { top: false, right: true, bottom: true, left: false, num: 160, v: true },
          { top: false, right: false, bottom: true, left: true, num: 221, v: true },
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: false, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: true, bottom: false, left: false, num: 152, v: true },
          { top: false, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: false, bottom: false, left: false, num: 152, v: true },
          { top: false, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: false, bottom: false, left: true, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: false, bottom: false, left: true, num: 259, v: true }
        ],
        [
          { top: true, right: true, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: false, left: true, num: 221, v: true },
          { top: false, right: false, bottom: true, left: false, num: 221, v: true },
          { top: false, right: true, bottom: true, left: false, num: 221, v: true },
          { top: true, right: false, bottom: true, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: false, num: 7, v: true },
          { top: true, right: false, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: false, num: 7, v: true },
          { top: true, right: true, bottom: false, left: true, num: 152, v: true },
          { top: false, right: true, bottom: true, left: true, num: 152, v: true },
          { top: false, right: false, bottom: false, left: true, num: 152, v: true },
          { top: false, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: true, bottom: true, left: true, num: 152, v: true },
          { top: false, right: true, bottom: false, left: true, num: 152, v: true },
          { top: true, right: true, bottom: false, left: true, num: 296, v: true },
          { top: false, right: true, bottom: true, left: true, num: 152, v: true },
          { top: true, right: false, bottom: false, left: true, num: 259, v: true },
          { top: false, right: false, bottom: true, left: false, num: 259, v: true }
        ],
        [
          { top: false, right: false, bottom: true, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: true, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: false, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: false, bottom: false, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: false, left: false, num: 7, v: true },
          { top: false, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: false, bottom: false, left: false, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: false, bottom: false, left: false, num: 152, v: true },
          { top: true, right: false, bottom: true, left: false, num: 152, v: true },
          { top: false, right: true, bottom: false, left: false, num: 152, v: true },
          { top: false, right: false, bottom: false, left: true, num: 296, v: true },
          { top: true, right: true, bottom: false, left: false, num: 296, v: true },
          { top: false, right: false, bottom: true, left: true, num: 259, v: true },
          { top: true, right: false, bottom: false, left: false, num: 259, v: true }
        ],
        [
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: false, bottom: true, left: true, num: 7, v: true },
          { top: false, right: false, bottom: false, left: false, num: 7, v: true },
          { top: true, right: false, bottom: false, left: false, num: 7, v: true },
          { top: false, right: true, bottom: true, left: false, num: 7, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: false, bottom: true, left: true, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: false, right: true, bottom: false, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: true, num: 296, v: true },
          { top: false, right: true, bottom: true, left: false, num: 296, v: true },
          { top: true, right: false, bottom: true, left: true, num: 259, v: true },
          { top: false, right: false, bottom: false, left: false, num: 259, v: true }
        ],
        [
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: true, left: true, num: 221, v: true },
          { top: false, right: true, bottom: true, left: false, num: 221, v: true },
          { top: false, right: false, bottom: true, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: false, right: true, bottom: true, left: true, num: 7, v: true },
          { top: true, right: false, bottom: false, left: true, num: 221, v: true },
          { top: true, right: true, bottom: true, left: false, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 221, v: true },
          { top: true, right: false, bottom: false, left: true, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: true, left: false, num: 221, v: true },
          { top: true, right: true, bottom: true, left: false, num: 221, v: true },
          { top: true, right: false, bottom: true, left: true, num: 152, v: true },
          { top: false, right: false, bottom: true, left: false, num: 152, v: true },
          { top: true, right: true, bottom: true, left: false, num: 152, v: true },
          { top: true, right: false, bottom: true, left: true, num: 259, v: true },
          { top: true, right: false, bottom: false, left: false, num: 259, v: true },
          { top: false, right: false, bottom: false, left: false, num: 259, v: true }
        ],
        [
          { top: false, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: true, bottom: true, left: false, num: 221, v: true },
          { top: true, right: false, bottom: true, left: true, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: true, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: true, left: true, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 221, v: true },
          { top: true, right: true, bottom: false, left: true, num: 373, v: true },
          { top: true, right: false, bottom: true, left: true, num: 373, v: true },
          { top: true, right: false, bottom: false, left: false, num: 373, v: true },
          { top: true, right: false, bottom: false, left: false, num: 373, v: true },
          { top: true, right: true, bottom: true, left: false, num: 373, v: true },
          { top: false, right: false, bottom: false, left: true, num: 259, v: true },
          { top: false, right: false, bottom: true, left: false, num: 259, v: true }
        ],
        [
          { top: false, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: true, bottom: false, left: true, num: 221, v: true },
          { top: false, right: false, bottom: false, left: true, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: false, left: false, num: 221, v: true },
          { top: true, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: false, left: false, num: 221, v: true },
          { top: false, right: true, bottom: false, left: false, num: 221, v: true },
          { top: false, right: false, bottom: false, left: true, num: 373, v: true },
          { top: true, right: false, bottom: false, left: false, num: 373, v: true },
          { top: false, right: false, bottom: false, left: false, num: 373, v: true },
          { top: false, right: true, bottom: false, left: false, num: 373, v: true },
          { top: true, right: false, bottom: false, left: true, num: 259, v: true },
          { top: false, right: false, bottom: false, left: false, num: 259, v: true },
          { top: true, right: false, bottom: false, left: false, num: 259, v: true }
        ]
      ]
      )

    const newMaze = maze.flatMap((row) => row.map((obj) => obj));

    useEffect(()=>{
        setInterval(()=>{
            setI(prevI=>prevI+1)
            console.log("WTF")
            console.log(i)
        },1000)
    },[])
    let m=0;
    const mazeElements=newMaze.map((tile)=>{
        // console.log(tile)
        let classes=[]
        Object.keys(tile).forEach(key=>{
            if(key!="num" && tile[key]==true){
                classes.push(key)
            }
        })
        if(m==189){
            classes.push("center")
        }
        m++
        return (
            <div className={`tile ${classes.join(' ')}`}> {tile.num}</div>
        )
    })

    return (
        <div className='grid'>
            {mazeElements}
        </div>
    )
}

export default App
